### ISSUE TITLE
Get "laughing" message on /callback

### ISSUE THREAD

**Issue by davidmead** [idno/Flickr#27]
After creating an app on Flickr, plugging in the API key & secret, adding the callback URL to workflow I just get the word "Laughing' on domain/flickr/callback when I try to connect.

Using Known 0.9.9-a.

**Comment by davidmead** [comment]
I waited a day and this is now connected. Maybe it was just Flickr's end just taking time.

**Comment by mapkyca** [comment]
Maybe... I'm a fan of whimsical error messages, but I doubt even I'd code an error like that!
